# This is a basic workflow to help you get started with Actions

name: Publish_Docker

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login Docker
        env:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        run: docker login --username=${username} --password=${password}

      - name: Build glibc2.19
        run: docker build --build-arg GLIBC_VERSION=2.19 -t skye231/glibc_builder64:2.19 -f ./Dockerfile-16.04 .
      - name: Push glibc2.19
        run: docker push skye231/glibc_builder64:2.19
        
      - name: Build glibc2.23
        run: docker build --build-arg GLIBC_VERSION=2.23 -t skye231/glibc_builder64:2.23 -f ./Dockerfile-16.04 .
      - name: Push glibc2.23
        run: docker push skye231/glibc_builder64:2.23
        
      - name: Build glibc2.24
        run: docker build --build-arg GLIBC_VERSION=2.24 -t skye231/glibc_builder64:2.24 -f ./Dockerfile-16.04 .
      - name: Push glibc2.24
        run: docker push skye231/glibc_builder64:2.24

      - name: Build glibc2.26
        run: docker build --build-arg GLIBC_VERSION=2.26 -t skye231/glibc_builder64:2.26 -f ./Dockerfile-16.04 .
      - name: Push glibc2.26
        run: docker push skye231/glibc_builder64:2.26
      
      - name: Build glibc2.27
        run: docker build --build-arg GLIBC_VERSION=2.27 -t skye231/glibc_builder64:2.27 -f ./Dockerfile .
      - name: Push glibc2.27
        run: docker push skye231/glibc_builder64:2.27

      - name: Build glibc2.28
        run: docker build --build-arg GLIBC_VERSION=2.28 -t skye231/glibc_builder64:2.28 -f ./Dockerfile .
      - name: Push glibc2.28
        run: docker push skye231/glibc_builder64:2.28

      - name: Build glibc2.29
        run: docker build --build-arg GLIBC_VERSION=2.29 -t skye231/glibc_builder64:2.29 -f ./Dockerfile .
      - name: Push glibc2.29
        run: docker push skye231/glibc_builder64:2.29

      - name: Build glibc2.30
        run: docker build --build-arg GLIBC_VERSION=2.30 -t skye231/glibc_builder64:2.30 -f ./Dockerfile .
      - name: Push glibc2.30
        run: docker push skye231/glibc_builder64:2.30
      
      - name: Build glibc2.31
        run: docker build --build-arg GLIBC_VERSION=2.31 -t skye231/glibc_builder64:2.31 -f ./Dockerfile .
      - name: Push glibc2.31
        run: docker push skye231/glibc_builder64:2.31

